export const patientRegistrationData = [
    {
        bsn: "999900377",
        name: "Coert Epping",
        initials: "Coert",
        surname: "Epping",
        dob: "15/06/2010",
        postcode: "9976VN",
        birthplace: "Druten",
        gender: "M",
        street: "Haven",
        number: "1",
        residence: "Lauwersoog",
    },
    {
        bsn: "999900389",
        name: "Deena van Bohemen",
        initials: "Deena",
        surname: "Bohemen",
        dob: "02/03/2012",
        postcode: "1276XV",
        birthplace: "Amstelveen",
        gender: "V",
        street: "Koedijk",
        number: "2",
        residence: "Huizen",
    },
    {
        bsn: "999900390",
        name: "Haider van Gameren",
        initials: "Haider",
        surname: "Gameren",
        dob: "09/01/2013",
        postcode: "3118LD",
        birthplace: "Amsterdam",
        gender: "M",
        street: "Van der Duyn van Maasdamstraat",
        number: "2",
        residence: "Schiedam",
    },
    {
        bsn: "999900419",
        name: "Maike Dorsman",
        initials: "Maike",
        surname: "Dorsman",
        dob: "28/04/2014",
        postcode: "2312XB",
        birthplace: "Wolvega",
        gender: "V",
        street: "Caeciliastraat",
        number: "1",
        residence: "Leiden",
    },
    {
        bsn: "999900420",
        name: "Anne-Ruth van de Kant",
        initials: "Anne-Ruth",
        surname: "Kant",
        dob: "07/11/2015",
        postcode: "2692AX",
        birthplace: "Warnsveld",
        gender: "M",
        street: "Zandveltweg",
        number: "146",
        residence: "s-Gravenzande",
    },
    {
        bsn: "999900432",
        name: "Alper Lem",
        initials: "Alper",
        surname: "Lem",
        dob: "12/02/1985",
        postcode: "6865WP",
        birthplace: "Arnhem",
        gender: "V",
        street: "Hertenstraat",
        number: "2",
        residence: "Doorwerth",
    },
    {
        bsn: "999900456",
        name: "Bente Lem",
        initials: "Bente",
        surname: "Lem",
        dob: "21/03/2021",
        postcode: "6865WP",
        birthplace: "Leeuwarden",
        gender: "V",
        street: "Hertenstraat",
        number: "2",
        residence: "Doorwerth",
    },
    {
        bsn: "999900468",
        name: "Aafke van de Lagemaat",
        initials: "Aafke",
        surname: "Lagemaat",
        dob: "14/03/2004",
        postcode: "3466LE",
        birthplace: "Drachten",
        gender: "M",
        street: "Mr. Pieter van Vollenhovestraat",
        number: "1",
        residence: "Waarder",
    },
    {
        bsn: "999900493",
        name: "Caspar Bourkan",
        initials: "Caspar",
        surname: "Bourkan",
        dob: "22/08/2003",
        postcode: "9917PK",
        birthplace: "Roosendaal",
        gender: "V",
        street: "Fennaweg",
        number: "1",
        residence: "Wirdum Gn",
    },
    {
        bsn: "999900511",
        name: "Meike Lem",
        initials: "Meike",
        surname: "Lem",
        dob: "09/01/2013",
        postcode: "6865WP",
        birthplace: "Leeuwarden",
        gender: "V",
        street: "Hertenstraat",
        number: "2",
        residence: "Doorwerth",
    },
    {
        bsn: "999900525",
        name: "Marilyn Bolten",
        initials: "21032021",
        surname: "Bolten",
        dob: "18/12/2002",
        postcode: "3161EZ",
        birthplace: "Kudelstaart",
        gender: "V",
        street: "Het Weegje",
        number: "3",
        residence: "Rhoon",
    },
    {
        bsn: "999900365",
        name: "Ferrie Goemans",
        initials: "Ferrie",
        surname: "Goemans",
        dob: "11/11/2001",
        postcode: "2692AX",
        birthplace: "Eindhoven",
        gender: "M",
        street: "Zandeveltweg",
        number: "146",
        residence: "s-Gravenzande",
    },
    {
        bsn: "999900444",
        name: "Johan Lem",
        initials: "Johan",
        surname: "Lem",
        dob: "13/02/1989",
        postcode: "6865WP",
        birthplace: "Makkum",
        gender: "M",
        street: "Hertenstraat",
        number: "2",
        residence: "Doorwerth",
    }
];